### PR TITLE
pull request to add updated indicators and add an optional moving average to the tuning process

### PR DESCRIPTION
**Pull request by wouldayajustlookatit**

### CODE REVIEW

**Comment by jmrichardson** [comment]
Yesterday I started coding a couple of major changes.  First I am replacing the correlation metric with distance correlation to capture non-linear correlation.  I am also replacing multi-objective optimization with kmeans clustering to choose parameter(s) that aren't on a cliff (ie not a lucky choice).  Also need to fix optuna for trials that are of the same parameter choice (https://github.com/optuna/optuna/issues/2021).  Once this done, will merge your changes.  BTW I based this update off your last PR

**Comment by iamkucuk** [comment]
> Yesterday I started coding a couple of major changes. First I am replacing the correlation metric with distance correlation to capture non-linear correlation. I am also replacing multi-objective optimization with kmeans clustering to choose parameter(s) that aren't on a cliff (ie not a lucky choice). Also need to fix optuna for trials that are of the same parameter choice ([optuna/optuna#2021](https://github.com/optuna/optuna/issues/2021)). Once this done, will merge your changes. BTW I based this update off your last PR

Waiting for this one impatiently!

**Comment by jmrichardson** [comment]
@wouldayajustlookatit @iamkucuk 

I created a development branch as first pass of the changes which include distance correlation, cluster method of selecting parameters and some bug fixes.  Would appreciate if you guys can take a test run and any PRs are much appreciated!

**Comment by jmrichardson** [comment]
The updates are now in main, if you like you can create a new pull request.  Let me know if you run into any issues

**Comment by iamkucuk** [comment]
@jmrichardson I just saw it. It seems effective changes are made. Can't wait to test it out!

**Comment by wouldayajustlookatit** [comment]
> Yesterday I started coding a couple of major changes. First I am replacing the correlation metric with distance correlation to capture non-linear correlation. I am also replacing multi-objective optimization with kmeans clustering to choose parameter(s) that aren't on a cliff (ie not a lucky choice). Also need to fix optuna for trials that are of the same parameter choice ([optuna/optuna#2021](https://github.com/optuna/optuna/issues/2021)). Once this done, will merge your changes. BTW I based this update off your last PR

I thought the multi-objective optimization was for time periods within the time series ie(days 0-10,11-20,etc)? Does the updated func work better for getting something like that?

**Pull request closed without merging**
